### ISSUE TITLE
Test runner is failing to publish the results.

### ISSUE THREAD

**Issue by chadrickman** [aloisdeniel/vsts-flutter-tasks#54]
```
Async Command Start: Publish test results
Async Command End: Publish test results
##[error]Unknown Test Runner.
##[debug]System.ArgumentException: Unknown Test Runner.
   at Microsoft.VisualStudio.Services.Agent.Worker.LegacyTestResults.LegacyTestRunDataPublisher.GetTestResultReader(String testRunner, Boolean publishRunLevelAttachments)
   at Microsoft.VisualStudio.Services.Agent.Worker.LegacyTestResults.LegacyTestRunDataPublisher.InitializePublisher(IExecutionContext context, String projectName, VssConnection connection, String testRunner, Boolean publishRunLevelAttachments)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.PublishTestResultsCommand.PublishTestRunDataAsync(String teamProject, TestRunContext testRunContext)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.WaitAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Run tests
```

**Comment by aloisdeniel** [comment]
Thanks for reporting.

I switched back to `JUnit` test publisher in a new published version, but since the API have changed, I have it is still working. 

Let me know!

**Comment by chadrickman** [comment]
Thanks @aloisdeniel I can confirm that this did not fix it and it's still throwing the same error.

**Comment by chadrickman** [comment]
@aloisdeniel This does appear to still be an issue. I'll run a build later tonight that has more logging to get more details. It's the same error though.

**Comment by xmashallax** [comment]
Still an issue here, same error as described above.

**Comment by skela** [comment]
Same here 
![84F8E03F-0780-482D-B65E-0607F769C2ED](https://user-images.githubusercontent.com/58268/81455540-d4841c00-918f-11ea-95c0-84e8ff493d91.png)

**Comment by alexaniko88** [comment]
What is the status of this?
We have the same problem here, all tests are passed but build fails because of **Unknown Test Runner** issue

**Comment by DavidFD005** [comment]
Same here

**Comment by jasperamorgan** [comment]
As a work around, you can run the tests without publishing the results.  To do this, comment out the Flutter test task and replace with this:

```
- task: CmdLine@2
        displayName: 'Flutter Test'
        inputs:
          script: '$(FlutterToolPath)/flutter test'
          workingDirectory: '$(Build.SourcesDirectory)'

##instead of##
# - task: aloisdeniel.flutter.flutter-test.FlutterTest@0
        # displayName: 'Flutter Test'
        # inputs:
          # projectDirectory: '$(Build.SourcesDirectory)'


```

**Comment by skela** [comment]
Is there a similar workaround, that works without having to modify the yaml?

**Comment by ezzabuzaid** [comment]
Same here, any updates

**Comment by cgravato** [comment]
I'm also getting this:
##[error]Unable to process command '##vso[results.publish type=flutter;mergeResults=false;publishRunAttachments=true;resultFiles=C:\azureagentx64\_work\2\s\junit.xml;testRunSystem=Flutter;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Unknown Test Runner.

**Comment by skela** [comment]
:facepalm: in case anyone cannot modify the yml to match what jaspermorgans workaround. It does work, just take notice that its not the same task, basically just running the unit test via command line. 
:facepalm:

**Comment by hey24sheep** [comment]
I have updated added a check for publish results [package](https://marketplace.visualstudio.com/items?itemName=Hey24sheep.flutter)

**Comment by josepmg** [comment]
> I have added a check for publish results in my [package](https://marketplace.visualstudio.com/items?itemName=Hey24sheep.flutter).

@hey24sheep could you give an example of how you did that? I'm a Azure DevOps Pipelines beginner hehe

**Comment by hey24sheep** [comment]
@josepmg  I have highlighted the checkbox also the add button. Read [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=net%2Cyaml%2Cbrowser%2Ctfs-2018-2) to get start easily. After that you could add "flutter tasks extension" and add "flutter test task". Check/Uncheck publish checkbox according to your need. 

![Annotation 2020-05-21 003447](https://user-images.githubusercontent.com/31468022/82486904-2a938080-9afb-11ea-86eb-60086369d1fd.png)

**Comment by josepmg** [comment]
> @josepmg I have highlighted the checkbox also the add button. Read [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=net%2Cyaml%2Cbrowser%2Ctfs-2018-2) to get start easily. After that you could add "flutter tasks extension" and add "flutter test task". Check/Uncheck publish checkbox according to your need.
> 
> ![Annotation 2020-05-21 003447](https://user-images.githubusercontent.com/31468022/82486904-2a938080-9afb-11ea-86eb-60086369d1fd.png)

Thanks, @hey24sheep I'll try it right away

**Comment by Tregan** [comment]
Temporary workaround (which also immediately improves the test report in the process) for me is to replace the Flutter Test task with these 3 tasks:

- PowerShell task that adds Flutter folders to PATH
```
Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};$(FLUTTERTOOLPATH);$(FLUTTERTOOLPATH)\cache\dart-sdk\bin;$(FLUTTERTOOLPATH)\..\.pub-cache\bin";
```
- Followed by a cmd task that activates [junitreport](https://pub.dev/packages/junitreport) and generates the test report
```
flutter pub get && flutter pub global activate junitreport && flutter test --machine | tojunit --output TEST-report.xml
```
- Publish Test Results task with search folder `$(System.DefaultWorkingDirectory)`

Even better: once https://github.com/flutter/flutter/issues/56675 is fixed it will even be possible to generate both a test report and coverage data at the same time by using `--machine --coverage`

This will especially be useful since I'm once again having issues making generation of the coverage data reliable, so I closed the PR for that.

**Comment by rspilker** [comment]
[junitreport version 1.3](https://pub.dev/packages/junitreport/versions/1.3.0), that has just been release, is capable of handling the output of `flutter test --machine --coverage`; it ignores the malformatted lines, generated by the extra `--coverage`.
